[package]
name = "stm32l0x1"
version = "0.0.1"
authors = ["WRansohoff"]
edition = "2018"

[dependencies]
bare-metal = "0.2.4"
cortex-m = "0.5.8"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "0.6.5"

[features]
rt = ["cortex-m-rt/device"]
